spring:
    application:
        name: zhouzh3-rocketmq4


rocketmq:
    name-server: 0.0.0.0:9876
    producer:
        group: rocketmq4-producer
        send-message-timeout: 3000
    consumer:
        group: rocketmq4-consumer
        pull-batch-size: 10
    client:
        log-use-slf4j: true