spring:
    application:
        name: zhouzh3-rocketmq4


rocketmq:
    name-server: 0.0.0.0:9876
    producer:
        group: order_tx_group
        send-message-timeout: 3000
    client:
        log-use-slf4j: true